name = "M_process"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"

#[[test]]
#name="runTests"
#source-dir="test"
#main="test_suite.f90"
#
#[[executable]]
#name="main"
#source-dir="apps/"
#main="main.f90"
#
#[[executable]]
#name="demo_process_readall"
#source-dir="PROGRAMS/demo_process_readall"
#main="demo_process_readall.f90"
#
#[[executable]]
#name="demo_M_process"
#source-dir="PROGRAMS/demo_M_process"
#main="demo_M_process.f90"
